import {Button, ListView, GridBox, HorizontalBox, VerticalBox} from "std-widgets.slint";

export struct GameItem :=
{
    name: string,
    path: string,
}

export global GameListData :=
{
    property<string> path;
    property<[GameItem]> list-of-roms: [{name: "snake.gb", path: "./snake.gb"}];
    callback button-pressed(string);
    callback select-directory();
}

export GameList := VerticalBox
{
    HorizontalBox
    {
        horizontal-stretch: 1;
        alignment: space-between;
        padding-top: 0px;
        padding-bottom: 0px;
        Text
        {
            vertical-stretch: 1;
            text: "Current Directory: " + GameListData.path;
            vertical-alignment: center;
            wrap: TextWrap.word-wrap;
        }
        VerticalBox
        {
            alignment: center;
            Button
            {
                text: "Choose...";
                clicked => { GameListData.select-directory(); }
            }
        }
    }
    ListView
    {
        for rom-item in GameListData.list-of-roms: VerticalLayout
        {
            HorizontalBox
            {
                alignment: space-between;
                Text
                {
                    text: rom-item.name;
                    font-size: 14px;
                    vertical-alignment: center;
                    overflow: TextOverflow.elide;
                }
                Button
                {
                    text: "Run";
                    font-size: 14px;
                    clicked => { GameListData.button-pressed(rom-item.path); }
                }
            }
        }
    }
}

export MainWindow := Window
{
    title: "Game Boy Inator";
    preferred-width: 500px;
    preferred-height: 500px;
    min-width: 250px;
    min-height: 250px;
    GameList{}
}
