import {Button, ListView} from "std-widgets.slint";

export struct GameItem :=
{
    name: string,
    path: string,
}

export MainWindow := Window
{
    title: "Game Boy Inator";
    preferred-width: 800px;
    preferred-height: 600px;

    property<[GameItem]> list-of-roms;
    callback button-pressed(string);

    ListView
    {
        for rom-item in list-of-roms: Button
        {
            text: rom-item.name;
            clicked => { button-pressed(rom-item.path); }
            preferred-width: 100px;
            preferred-height: 75px;
        }
    }
}